config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views
app_name = 'main'
urlpatterns = [
    path("", views.HomeView.as_view(), name='home'),
    path("login/",views.log_in, name='login'),
    path("logout/",views.log_out, name='logout'),
    path("about/", views.AboutView.as_view(), name='about'),
    path("contact/", views.Contact.as_view(), name='contact'),
    
    path('player/<slug:slug>', views.PlayerDetailView.as_view(), name='player_detail'),
    path('club/<str:name>', views.ClubListView.as_view(),name='club_list')
]

main/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True)
    flag = models.ImageField(upload_to='flags/', default='default/no_flag.png')

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return str(self.name)

# Club
class Club(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True)
    logo = models.ImageField(upload_to='club_logos/', default='default/club_logo.png')

    def __str__(self):
        return str(self.name)

class Player(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100,unique=True)
    image = models.ImageField(upload_to='player_images/%Y/%m', default='default/no_user.png')
    country = models.ForeignKey(
        Country, on_delete=models.PROTECT, related_name='players_of_country')
    club = models.ForeignKey(
        Club, on_delete=models.PROTECT, related_name='players')
    age = models.PositiveIntegerField(default=0)
    rating = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.name)

main/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView,DetailView
from .models import Country, Player, Club
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout




def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.get(username=username)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login( request, user)
            return redirect('main:home')
    context = {}
    return render(request, "log_in.html", context)

def log_out(request):
    logout(request)
    return redirect('main:home')



# def HomeView(request):
#     if request.GET.get('q') != None:
#         q = request.GET.get('q')
#     else:
#         q = ' '
#     player = Player.objects.filter(
#         name__icontains = q
#     )
#     count = player.count()    
#     context = {"player":player}
#     return render(request, "index.html", context)
#     print(player)





class HomeView(ListView):
    model = Player
    template_name = 'index.html'
    context_object_name = 'players'
    paginate_by = 4
    # context_object_name = {"play÷er", "image"}
    
    def get_queryset(self):
        player = Player.objects.all()
        return player
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clubs"] = Club.objects.all()
        return context

class PlayerDetailView(DetailView):
    model = Player


class ClubListView(ListView):
    model = Player
    template_name = "index.html"
    paginate_by = 3
    
    def get_queryset(self):
        print(self.request.body)
        return Player.objects.all()
    
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context["object_list"] = Player.objects.filter(name=kwargs.get("name"))
       return context
   
    
    

class AboutView(TemplateView):
    template_name = 'about.html'
class Contact(TemplateView):
    template_name = 'contact.html'
    
# Create your views here.

templates/about.html
{% extends 'base.html'%}
{% block content %}
<h1>About</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
      {# Load the tag library #}
    {% load bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            list-style: none;
        }
        .container1{
        padding: 2% 5%;
        }
        .name{
            display: flex;
            border: 1px solid gray;
            column-gap: 20px;
        }
        nav{
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        nav button{
            background-color: blue;
            color: white;
            outline: none;
            border: none;
            width: 70px;
            height: 35px;
            border-radius: 10px;
        }
        nav button a{
            color: white;
            text-decoration: none;
        }
        button:hover{
            transform: scale(1.05);
        }
        .loginForm form{
            display: flex;
            flex-direction: column;
            row-gap: 20px;
            width: 400px;
        }
        .loginForm{
            background-color: rgb(31, 31, 31);
            padding: 10px 10px;
            width: 450px;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0 auto;
            padding: 10% 5%;
        }
        .loginForm .input{
            outline: none;
            padding: 2% 2%;
            border-radius: 10px;
            border: none;
        }
        .loginForm form #type{
            background-color: blue;
            border: none;
            color: white;
            padding: 2% 2%;
            border-radius: 10px;
        }

        .player{
            display: flex;
            column-gap: 50px;
            
        }
    </style>
</head>
<body>
        {% include 'navbar.html'%}

     <div class="container1">
        {% block content%}

        {% endblock%}
       </div>
</body>
</html>

templates/contact.html
{% extends 'base.html'%}
{% block content%}
    <h4>Contact</h4>
{% endblock content%}

templates/index.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
  <h1>Players Table</h1>
<div>
  {% for club in clubs %}
  <a href="{% url 'main:club_list' club.name %}">
    <img src="{{club.logo.url}}" width="30" alt="">
    {{club.name}}
  </a>
  {% endfor %}
</div>
<br>
<div class="player">
    {% for object in page_obj %}
  <div class="one">
        <div>
          <a href="{% url 'main:player_detail' object.slug %}">
          <img src="{{object.image.url}}" alt="{{object.name}}" width="100">
          </a>
        </div>
        <div>{{object.name}}</div>
        <div>{{object.country}}</div>
        <div>{{object.club}}</div>
        <div>{{object.age}}</div>
        <div>{{object.rating}}</div>
    </div>
    {% endfor%}
  </div>
</div>
<div class="pagination">
  <span class="step-links">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          {% for page in page_obj.paginator.page_range %}
          <a href="?page={{page}}" 
          style='{% if page == page_obj.number %}background-color:khaki;{% endif %}'>{{page}}</a>
          {% endfor %}

      <span class="current">
        <span >
          {{ page_obj.number }}
        </span>
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>
</div>
{% endblock %}

templates/log_in.html
{%extends 'base.html'%}
{%block content%}
<div class="loginForm">
    <form action="" method="POST">
        {% csrf_token %}
        <input class="input" type="text" name="username" placeholder="Enter username">
        <input class="input" type="text" name="password" placeholder="Enter password">
        <input id="type" type="submit">
    </form>
</div>
{%endblock%}

templates/main/player_detail.html
{% extends 'base.html'%}
{% block content %}

    <div class="container">
        <div class="one">
            <div><img src="{{object.image.url}}" alt=""></div>
            <div>{{object.name}}</div>
            <div>{{player.country}}</div>
            <div>{{object.club}}</div>
            <div>{{object.age}}</div>
            <div>{{object.rating}}</div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
<header class="bg-dark">
    <div class="container py-2">
       <nav>
           <ul class="nav">
               <li class="nav-item">
                   <a href="{% url 'main:home' %}" class="nav-link fw-bold fs-5">Home</a>
               </li>
               <li class="nav-item">
                   <a href="{% url 'main:about' %}" class="nav-link fw-bold fs-5">About</a>
               </li>
               <li class="nav-item">
                   <a href="{% url 'main:contact'%}" class="nav-link fw-bold fs-5">Contact {{test_text}}</a>
               </li>
           </ul>
           <div>
            <form action="{% url 'main:home' %}">
                <input type="text" name="q">
            </form>
           </div>
           <div>
        {% if request.user.is_authenticated %}
           <button> <a href="{% url 'main:logout' %}">Logout</a></button>
            {%else%}
           <button><a href="{% url 'main:login' %}">LogIn</a></button>
           {%endif%}
           </div>
       </nav>
    </div>
</header>